name: Deploy to EC2

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP: 98.82.190.123
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the app code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        echo "$SSH_PRIVATE_KEY" > mykey.pem
        chmod 600 mykey.pem

    - name: Copy application files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i mykey.pem -r * ubuntu@$EC2_PUBLIC_IP:~/NetflixMovieCatalog/

    - name: Run deployment script on EC2
      run: |
        ssh -i mykey.pem ubuntu@$EC2_PUBLIC_IP << 'EOF'
          cd ~/NetflixMovieCatalog
          bash deploy.sh
        EOF
