name: Netflix Movie Catalog Service Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Replace with your actual secret key if needed

    - name: Copy Nginx configuration file to EC2
      run: |
        scp -o StrictHostKeyChecking=no ./nginx-config/default.conf ubuntu@<98.82.190.123>:/home/ubuntu/default.conf

    - name: Update Nginx configuration on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@<98.82.190.123> << EOF
          sudo cp /home/ubuntu/default.conf /etc/nginx/conf.d/default.conf
          sudo nginx -t
          if [ $? -eq 0 ]; then
            sudo systemctl restart nginx
            echo "Nginx configuration is correct. Nginx restarted."
          else
            echo "Nginx configuration failed. Please check the config file."
            exit 1
          fi
        EOF
