name: Netflix Movie Catalog Service Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nginx
      run: sudo apt update && sudo apt install -y nginx

    - name: Start Nginx
      run: sudo systemctl start nginx

    - name: Copy Nginx config file
      run: sudo cp ./nginx-config/default.conf /etc/nginx/conf.d/default.conf

    - name: Test Nginx configuration
      run: sudo nginx -t

    - name: Restart Nginx
      run: sudo systemctl restart nginx
